### ISSUE TITLE
Tips on how to run it locally?

### ISSUE THREAD

**Issue by ccjcan** [leoBitto/DjangoForge#7]
Hi, trying your codebase and was wondering if you can give me tips on how to run it locally. Or how I can change settings.py to make it work locally. the logging_app seems to be missing.

**Comment by leoBitto** [comment]
logging_app is set as submodule so when you do clone you should use the --recursive like this:
`git clone --recurse-submodules https://github.com/leoBitto/DjangoForge.git`

you should then have the logging_app.

remember that both DjangoForge and logging_app are in development phase. especially logging_app is not compliant with GDPR (if you are in Europe) and require some work to do. 

as the time of writing this i'm focusing on making DjangoForge easily deployable with a system of containers. the latest version is not really functioning... I'm trying to create a better version and it broke somewhere. 
As it is a side project from my work i don't have a lot of time to fix this, but i like to collaborate :)
this is the original tutorial i started following, many others have followed but i think i will implement these ideas once again and see where it leads.

have you tried the script manager.sh? use :
`sudo source manager.sh build`

it should create the images and you should be able to connect locally at http://localhost

it works with docker so settings.py should not be touched
